config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, :email, presence: true
  validates :username, :email, uniqueness: { case_sensitive: false }
  validates :username, length: { minimum: 3, maximum: 25 }
  validates :email, length: { maximum: 105 }
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: [:show, :index]
  before_action :require_article_author, only: [:edit, :update, :destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end

    def require_article_author
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You only can modify your own articles!"
        redirect_to @article
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in succesfully"
      redirect_to user
    else
      flash.now[:alert] = "There were something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    flash[:notice] = "Logged Out"
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 2)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 2)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: "Wellcome #{@user.username}!" }
        format.json { render :new, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "You acccount data hass been succesfully updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all articles has been deleted!"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You only can modify your own account!"
      redirect_to current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5::hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <% if logged_in? && (article.user == current_user || current_user.admin?)%>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <%= render 'messages/errors', obj: article %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article' %>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) if logged_in? && (@article.user == current_user || current_user.admin?) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_navigation.html.erb
<div class="navbar">
  <%= link_to "Alpha Blog", root_path %>
  <%= link_to "Bloggers", users_path %>
  <div class="dropdown">
    <button class="dropbtn"> Articles
        <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
        <%= link_to "Create New Article", new_article_path if logged_in? %>
        <%= link_to "View Articles", articles_path %>
    </div>
  </div>
    <% if logged_in? %>
        <div class="dropdown">
            <button class="dropbtn">
                <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
                 <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <%= link_to "View your Profile", user_path(current_user) %>
                <%= link_to "Edit Your Profile", edit_user_path(current_user) %>
                <%= link_to "Delete Your Profile", user_path(current_user), method: :delete, data: { confirm: "Are you sure?" }%>
            </div>
        </div>
        <%= link_to "Log out" , logout_path, method: :delete %>
    <% else %>
        <%= link_to "Log In" , login_path %>
        <%= link_to "Sign Up" , signup_path %>
    <% end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="nav-bar"> <%= render 'layouts/navigation' %> </div>
    <div id="app">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(obj.errors.count, "error") %> prohibited this #{obj.class.name.downcase} from being saved:</h2>

    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/pages/about.html.erb
<h1> This is About page </h1>

app/views/pages/home.html.erb
<h1> This is Home page </h1>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |form| %>
  <%= render 'messages/errors', obj: @user %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit(@user.new_record? ? "Sign Up" : "Update Account") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1> Edit your profile </h1>

<%= render 'form', article: @article %>

app/views/users/index.html.erb
<h1> Alpha Bloggers </h1>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

<div>
  <% @users.each do |user| %>
    <div class="users">
      <div class="user-name">
        <%= link_to user.username, user %>
      </div>
    </div>
    <div class="user-gravatar"> 
      <%=link_to gravatar_for(user, size: 150), user %>
    </div>
    <div class="articles-count"> 
      <%= pluralize(user.articles.count, "article") %> 
    </div>
    <div class="articles-actions"> 
      <span> <%= link_to "View Profile", user %>
      </span> <%= link_to "Edit Profile", edit_user_path(user) if logged_in? && (user == current_user || current_user.admin?) %><span></span>
      </span> <%= link_to "Delete Profile", user_path(user), method: :delete if logged_in? && (user == current_user || current_user.admin?) %><span></span>
    </div>
    <div class="user-created-at"> Joined <%= time_ago_in_words(user.created_at) %> ago </div>
  <% end %>
</div>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1> Signup </h1>

<%= render 'form', obj: @user %>

app/views/users/show.html.erb
<h1> <%= @user.username %>'s profile </h1>

<%= gravatar_for @user, size: 200 %>

<div> <%= link_to "Edit my profile", edit_user_path if logged_in? && (@user == current_user || current_user.admin?) %> </div>

<h3> Articles </h3>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<div> <%= link_to "Logout", logout_path, method: :delete %> </div>